# Site settings
title: apm
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alexandre Maros
user_description: That guys that likes to do a bit of everything.
user_title: Computer Scientist
instagram: alepmaros
flickr: alehhh
github_username:  alepmaros
linkedin: alexandre-maros-77b558110

# Google-analytics
google-analytics:
  id: "UA-73124143-1"

exclude: ['package.json', 'src' , 'node_modules']
